services:
  - type: web
    name: policy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: RELOAD
        value: "false"
